environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version && npm --version
  - npm test

build: off

matrix:
  fast_finish: true

cache:
  - node_modules -> appveyor.yml,package.json,package-lock.json
  
